trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'  # Use a Microsoft-hosted agent if you're not using a self-hosted pool

variables:
  - group: devjobs-grp
  - name: TF_VERSION
    value: '1.6.6'
  - name: backendServiceArm
    value: 'devjobsConnection'

steps:
# Install specified Terraform version
- task: TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: $(TF_VERSION)

# Terraform Init
- task: TerraformCLI@1
  displayName: 'Terraform Init'
  inputs:
    command: 'init'
    provider: 'azurerm'
    backendServiceArm: $(backendServiceArm)
    backendAzureRmResourceGroupName: 'PTutorial-rg'
    backendAzureRmStorageAccountName: 'ptutorial321'
    backendAzureRmContainerName: 'ptstate'
    backendAzureRmKey: 'terraform.tfstate'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

# Terraform Plan
- task: TerraformCLI@1
  displayName: 'Terraform Plan'
  inputs:
    command: 'plan'
    provider: 'azurerm'
    environmentServiceNameAzureRM: $(backendServiceArm)
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    args: '-out=tfplan'

# Publish Plan as artifact (optional but useful for approvals)
- task: PublishPipelineArtifact@1
  displayName: 'Publish Terraform Plan'
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/tfplan'
    artifact: 'tfplan'
    publishLocation: 'pipeline'

# Terraform Apply
- task: TerraformCLI@1
  displayName: 'Terraform Apply'
  inputs:
    command: 'apply'
    provider: 'azurerm'
    environmentServiceNameAzureRM: $(backendServiceArm)
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    args: 'tfplan -auto-approve'
